Convert banner to field warning
MatmaRex/patchdemo pull request #123
Opened 2020-09-25 13:48 UTC by edg2s

2020-09-25 13:49 UTC, edg2s commented
Before:
![image](https://user-images.githubusercontent.com/180672/94274878-2a3e4280-ff3e-11ea-9dbd-caf1e59aef9f.png)
After:
![image](https://user-images.githubusercontent.com/180672/94274897-332f1400-ff3e-11ea-9c8e-6a3e27d07ce6.png)

2020-09-25 16:37 UTC, MatmaRex commented
I know it's a small change, but I really hate it.

2020-09-25 18:13 UTC, edg2s commented
> I know it's a small change, but I really hate it.

Tell me what you really think though.

2020-09-25 18:13 UTC, edg2s commented
What about an info icon? I think it should probably match the width of the form either way?

2020-09-29 23:12 UTC, MatmaRex commented
Really please no

If it should match the width of the form, then I think the form should be allowed to be wider. I'm actually not sure why its width was limited, when the width of the whole page is also already limited? I feel like it would be fine if it was expanded from `50em` to `1100px`, like the table and everything else.

2020-10-01 12:16 UTC, edg2s commented
> If it should match the width of the form, then I think the form should be allowed to be wider. I'm actually not sure why its width was limited, 

Forms becomes harder to use when you make them too wide. Either the labels are too far from the inputs, or the inputs are too wide and the select handle is too far from the labels.

2021-01-02 20:08 UTC, MatmaRex requested changes

2021-01-02 20:08 UTC, MatmaRex commented on index.css
> +/* T263737 */
No longer needed?

2021-01-02 20:09 UTC, MatmaRex commented
I'm still not convinced that this is an improvement.

2022-01-25 23:31 UTC, MatmaRex commented
Ah, whatever.

2022-01-25 23:31 UTC, merged