Try to use consistent casing for "Patch demo"
MatmaRex/patchdemo pull request #348
Opened 2021-11-11 00:06 UTC by edg2s

The username "Patch Demo" would probably be annoying to
change at this point.

2021-11-15 22:34 UTC, MatmaRex requested changes

2021-11-15 22:34 UTC, MatmaRex commented on new/install.sh
> +"$WIKINAME" "Patch demo"
This is the username, actually.

2021-11-20 12:56 UTC, edg2s commented on new/install.sh
> +"$WIKINAME" "Patch demo"
Fixed

2021-11-22 22:41 UTC, MatmaRex approved these changes

2021-11-22 22:42 UTC, merged