Allow enabling temp user creation for IP Masking QA
MatmaRex/patchdemo pull request #517
Opened 2023-01-10 16:09 UTC by kostajh

Bug: T326651

2023-01-10 18:24 UTC, Tchanders reviewed
This looks good to me - thanks @kostajh

2023-01-10 18:28 UTC, edg2s requested changes

2023-01-10 18:28 UTC, edg2s commented on new/postinstall.sh
> +# Enable temp user creation if selected
"'Enable temporary user account creation (IP Masking)"

2023-01-10 18:28 UTC, edg2s commented on new/postinstall.sh
> +  cp $PATCHDEMO/localsettings/feature-tempuser.php $PATCHDEMO/wikis/$NAME/w/settings.d
use tabs

2023-01-11 01:21 UTC, merged

2023-01-11 01:24 UTC, MatmaRex commented
Thanks for doing this!

Just for the record, I'm not a fan of adding more options to the Patch demo form – it's already so long, it barely fits on a 1080p screen. I'd usually suggest creating a "do not merge" Gerrit changeset somewhere that changes the MediaWiki defaults, and can be combined with other patches for Patch demo.

I am, however, a fan of the IP Masking project, and if this helps move it forward, then I'm for it.

![image](https://user-images.githubusercontent.com/160413/211696060-772639a5-2954-41ac-917b-6a2ec0297dff.png)

2023-01-11 13:58 UTC, edg2s commented
I have a local patch to collapse everything below "Choose included repos" into an "Advanced" section. Thoughts @MatmaRex ?

2023-01-12 19:49 UTC, MatmaRex commented
Sounds okay to me, but I don't know how everyone who wanted these options added will feel about it ;)

2023-01-12 20:28 UTC, kostajh commented
> I'd usually suggest creating a "do not merge" Gerrit changeset somewhere that changes the MediaWiki defaults, and can be combined with other patches for Patch demo.

That seems tricky for non-technical users who want to preview or QA patches.

> I have a local patch to collapse everything below "Choose included repos" into an "Advanced" section.

That sounds like a good idea to me.