Ignore dependencies on unknown repositories
MatmaRex/patchdemo pull request #577
Opened 2023-06-29 10:50 UTC by MatmaRex

Sometimes folks point 'Depends-On' entries to Wikimedia config repositories. We don't support them, but these dependencies are usually not needed to test a patch on Patch demo, so ignore them instead of erroring out.

Closes #573

2023-07-03 23:33 UTC, MatmaRex commented
Thoughts? @edg2s

2023-07-04 22:22 UTC, edg2s requested changes

2023-07-04 22:22 UTC, edg2s commented on new.php
> +			echo "<p>Ignoring a patch from <em>$repoHtml</em></p>";
Use `warn()` instead?

2023-07-05 17:55 UTC, MatmaRex commented on new.php
> +			echo "<p>Ignoring a patch from <em>$repoHtml</em></p>";
Oh, I forgot we have that.

2023-07-30 08:01 UTC, merged